version: "3.9"

services:
  kubf-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kubf-blue
    expose:
      - "9002"
    environment:
      - PROD_DATASOURCE_URL=${PROD_DATASOURCE_URL}
      - PROD_DATASOURCE_USERNAME=${PROD_DATASOURCE_USERNAME}
      - PROD_DATASOURCE_PASSWORD=${PROD_DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  kubf-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kubf-green
    expose:
      - "9002"
    environment:
      - PROD_DATASOURCE_URL=${PROD_DATASOURCE_URL}
      - PROD_DATASOURCE_USERNAME=${PROD_DATASOURCE_USERNAME}
      - PROD_DATASOURCE_PASSWORD=${PROD_DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always