server {
    listen 80;
    server_name ku-barrierfree.site www.ku-barrierfree.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ku-barrierfree.site www.ku-barrierfree.site;

    ssl_certificate /etc/letsencrypt/live/ku-barrierfree.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ku-barrierfree.site/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        proxy_pass http://localhost:9002;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
    }
}