name: KU-Barrier-Free CD with Gradle and Docker

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ☕️ set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          setting-path: ${{ github.workspace }}

      - name: 👏🏻 grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🐘 build with Gradle (without test)
        run: ./gradlew clean build -x test --stacktrace

      - name: 🐳 Docker image build & push
        run:  |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: 📦 Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu"

      - name: 🚀 deploy to prod-server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          envs: GITHUB_SHA
          script: |
            echo "📦 Checking current container"
            source /home/ubuntu/scripts/choose_container.sh
            
            echo "🟢 NEW_CONTAINER: $NEW_CONTAINER"
            echo "⚫️ OLD_CONTAINER: $OLD_CONTAINER"
            echo "📦 NEW_PORT: $NEW_PORT"
            
            echo "📄 Writing .env file"
            echo "NEW_CONTAINER=$NEW_CONTAINER" > /home/ubuntu/.env
            echo "NEW_PORT=$NEW_PORT" >> /home/ubuntu/.env
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> /home/ubuntu/.env
            echo "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}" >> /home/ubuntu/.env
            echo "PROD_DATASOURCE_URL=${{ secrets.PROD_DATASOURCE_URL }}" >> /home/ubuntu/.env
            echo "PROD_DATASOURCE_USERNAME=${{ secrets.PROD_DATASOURCE_USERNAME }}" >> /home/ubuntu/.env
            echo "PROD_DATASOURCE_PASSWORD=${{ secrets.PROD_DATASOURCE_PASSWORD }}" >> /home/ubuntu/.env
            
            echo "🐳 Pulling latest Docker image from DockerHub"
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
            
            echo "🚀 Starting new container: $NEW_CONTAINER"
            docker compose --env-file /home/ubuntu/.env -f docker-compose.yml pull
            docker compose --env-file /home/ubuntu/.env -f docker-compose.yml up -d
            
            echo "🧪 Waiting for $NEW_CONTAINER to pass health check"
            bash /home/ubuntu/scripts/health_check.sh $NEW_PORT $NEW_CONTAINER $OLD_CONTAINER || exit 1
            
            echo "📝 Updating Nginx config to point to port $NEW_PORT"
            echo "proxy_pass http://localhost:$NEW_PORT;" > /tmp/proxy_pass_line
            sudo sed -i '/proxy_pass/c\\t\tproxy_pass http://localhost:'"$NEW_PORT"';' /etc/nginx/conf.d/app.conf
            sudo nginx -t && sudo systemctl reload nginx
            
            echo "🚮 Clean up old container"
            if docker ps -a --format '{{.Names}}' | grep -q "$OLD_CONTAINER"; then
              docker stop $OLD_CONTAINER
              docker rm $OLD_CONTAINER
            fi
            docker image prune -a -f